code/blocipedia/config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'
  get 'charges/edit'

  resources :wikis do
    resources :collaborators
  end
  
  resources :charges, only: [:new, :create]
  delete '/downgrade', to: 'charges#downgrade'

  root to: "main#index"
    devise_for :users

end

code/blocipedia/app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

code/blocipedia/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :wikis
  has_many :collaborators
  
  before_save { self.role ||= :standard }
  
  enum role: [:admin, :premium, :standard]
end

code/blocipedia/app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  def all_users
      available = []
      
      @wiki = Wiki.find(id)
      User.where.not(name: @wiki.user.name).order(name: :asc).each do |user|
        if !users.include?(user)
          available << user 
        end
      end

      return available
  end
end

code/blocipedia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_paramaters, if: :devise_controller?
  
  protected
  
    def configure_permitted_paramaters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end
end

code/blocipedia/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  after_action :make_premium, only: :create
  
  def new
    role = current_user.role
    case role
      when "standard"
        @stripe_btn_data = {
          key: "#{ Rails.configuration.stripe[:publishable_key] }",
          description: "Premium Membership - #{current_user.name}",
          amount: 15_00
        } 
      when "premium"
        flash[:alert] = "You are already signed up as a Premium member!"
        redirect_to root_path
    end
  end
  
  def create
    @user = current_user
    
    # Creates a Stripe Customer object, for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 15_00,
      description: "Upgrade to Premium Membership - #{current_user.email}",
      currency: 'usd'
    )
    
    flash[:notice] = "Thank you for you payment, #{current_user.email}! You can now create and edit private wikis."
    redirect_to root_path
    
    # Stripe will send back CardErrors when something goes wrong. This block catches and displays the errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
  
  def edit
  end
  
  def downgrade
    current_user.update_attributes(role: 'standard')
    flash[:notice] = "You've been downgraded to standard membership."
    redirect_to root_path
    
    @user_wikis = current_user.wikis.where(private: true)
    @user_wikis.each do |p|
      p.update_attributes(private: false)
    end
  end
  
  private
  
  def make_premium
    current_user.update_attribute(:role, 'premium')
  end
  
end

code/blocipedia/app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  
  def new
    @collaborator = @wiki.collaborators.new
  end
  
  def show
    @collaborator = Collaborator.find(params[:id])
  end
  
  def create
    @collaborator = @wiki.collaborators.new(collaborator_params)
    
    if @collaborator.save
      flash[:notice] = "#{@collaborator.user.name} was added as a collaborator to this wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error adding the collaborator. Please try again."
      redirect_to @wiki
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    
    if @collaborator.destroy
      flash[:notice] = "#{@collaborator.user.name} was removed from this wiki."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error removing the collaborator. Please try again."
      redirect_to @wiki
    end
  end
  
  private
  
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
  
  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end
end

code/blocipedia/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

code/blocipedia/app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id]);
  end

  def new
    @wiki = Wiki.new
  end
  
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    
    if current_user.standard?
      @wiki.update_attribute(:private, false)
    end
    
    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    
    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the post."
      render :show
    end
  end
  
  private
  
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

code/blocipedia/app/helpers/application_helper.rb
module ApplicationHelper
    def markdown_to_html(markdown)
      renderer = Redcarpet::Render::HTML.new
      extensions = {fenced_code_blocks: true}
      redcarpet = Redcarpet::Markdown.new(renderer, extensions)
      (redcarpet.render markdown).html_safe
    end
end

code/blocipedia/app/helpers/charges_helper.rb
module ChargesHelper
end

code/blocipedia/app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

code/blocipedia/app/helpers/main_helper.rb
module MainHelper
end

code/blocipedia/app/helpers/wikis_helper.rb
module WikisHelper
end

code/blocipedia/app/views/charges/_form.html.erb
<% if current_user.role == "standard" %>
<h4>Upgrade to Premium Membership</h4>
    <ul>
        <li>Create private wikis.</li>
        <li>Add and remove collaborators to your private wikis.</li>
        <li>The one-time cost to sign up is 15 dollars.</li>
    </ul>
    <br/>
<% end %>

<% if current_user.role == "premium" %>
    <h4>Downgrade to Standard Membership</h4>
    <p>
        If you downgrade:
    </p>
    <ul>
        <li>You will no longer be able to create private wikis and add/remove collaborators to them.</li>
        <li>Your private wikis will become public.</li>
    </ul>
    <br/>
<% end %>

code/blocipedia/app/views/charges/edit.html.erb
<h4>Your current membership is: <%= current_user.role %></h4>
<br />

<%= render partial: 'charges/form' %>

<% if current_user.role == "standard" %>
    <%= link_to "Upgrade", charges_new_path, class: 'btn btn-primary' %>
<% end %>

<% if current_user.role == "premium" %>
    <%= link_to "Downgrade", downgrade_path, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade to a standard membership?'} %>
<% end %>

code/blocipedia/app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    
    <%= render partial: 'charges/form' %>
    
    <div>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
    </div>

    <% content_for :analytic do %>
        <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Payment Page Visit"); }); </script>
    <% end %>
<% end %>

code/blocipedia/app/views/collaborators/_collaborator.html.erb
<%= content_tag :tbody, class: 'media', id: "collaborator-#{collaborator.id}" do %>
    <tr>
        <td class="col-md-1"><center><%= link_to "", "/wikis/#{@wiki.id}/collaborators/#{collaborator.id}", method: :delete, class: 'glyphicon glyphicon-remove', remote: true %></center></td>
        <td class="col-md-6"><%= collaborator.user.name %></td>
    </tr>

<% end %>

code/blocipedia/app/views/collaborators/_form.html.erb
<%= form_for [@wiki, Collaborator.new()] do |f| %>

<div class="row">
    <div class="col-md-7">
        <h3>Collaborators</h3>
    </div>
    
    <div class="col-md-5">
        <h3>Add a Collaborator</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-7">
        <table class="table table-bordered">
            <thead> 
                <tr>
                    <th class="col-xs-1">Remove?</th>
                    <th class="col-xs-6">Collaborator</th>
                </tr>
            </thead> 
                <%= render @wiki.collaborators %>
        </table>
    </div>

    <div class="col-md-5">
        <%= form_for [@wiki, Collaborator.new()] do |f| %>
            <h4>
                <%= f.collection_select :user_id, @wiki.all_users, :id, :name, :prompt => true %>
            </h4>

            <div class="form-group">
                <%= f.submit "Save", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
</div>
<% end %>

code/blocipedia/app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

code/blocipedia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>
  </head>
<body class="<% if user_signed_in? %>signed-in<% end %> <% if current_page?('/users/edit') %>edit-page<% end %>">
  <div class="container">
    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
      <% unless current_page?(root_path) %>
        <li><%= link_to "Blocipedia", root_path %></li>
      <% end %>
      <% unless current_page?(wikis_path) %>
        <li><%= link_to "Wikis", wikis_path %></li>
      <% end %>
      <li><%= link_to 'Edit account', edit_user_registration_path, :class => 'edit-account-link' %></li>
      <% if current_user.role != "admin" && !current_page?(charges_edit_path) %>
        <li><%= link_to "Membership", charges_edit_path %></li>
      <% end %>
      <% end %>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          <div class="pull-right">
            Signed in as: <strong><%= current_user.name %></strong> |
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </div>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>
    
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
 </div>

</body>
</html>

code/blocipedia/app/views/main/index.html.erb
<br>
<div class="jumbotron">
    <h1>Blocipedia</h1>
    <p>Blocipedia allows you to create your own wikis and share them with others.</p>
    <% if !user_signed_in? %>
        <p><%= link_to "Sign In", new_user_registration_path %> or
        <%= link_to "Sign Up", new_user_session_path, class: 'btn btn-primary' %> today!</p>
    <% end %>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Public Wikis</h2>
        <p>Create public wikis to share with others.</p>
    </div>
    <div class="col-md-5">
        <h2>Private Wikis</h2>
            <p>Create private wikis when signed up as a premium member.</p>
            <p>Add and remove collaborators to your private wikis.</p>
            <% if user_signed_in? %>
                <% if current_user.role != "admin" %>
                    <%= link_to "Upgrade", charges_new_path, class: 'btn btn-primary' %>
                <% end %>
            <% end %>
    </div>
    <div class="col-md-3">
        <h2>Markdown Support</h2>
         <p>Edit your wikis using Markdown.</p>
    </div>
</div>

code/blocipedia/app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
    <% if current_page?(new_wiki_path) %>
        <% if current_user.admin? || current_user.premium? %>
            <% page = "new" %>
        <% end %>
    <% elsif current_page?(edit_wiki_path) %>
        <% if current_user.admin? || (current_user.premium? && @wiki.user == current_user) %>
            <% page = "edit" %>
        <% end %>
    <% end %>
    
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
    
    <div class="row">
        <div class="col-md-8">
            <% if page == "new" || page == "edit" %>
                <div class="form-group" style="margin-left:20px">
                    <%= f.label :private, class: 'checkbox' do %>
                        <%= f.check_box :private, {}, "true", "false" %> Private wiki
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
    
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>

<% end %>

code/blocipedia/app/views/wikis/edit.html.erb
<center><h1>Edit Wiki</h1></center>

<div class="row">
    <div class="col-md-8">
        <%= render partial: 'wikis/form' %>
    </div>
</div>

code/blocipedia/app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
    <div class="col-md-8">
        <% @wikis.each do |wiki| %>
            <h4 class="media-heading">
                <%= link_to markdown_to_html(wiki.title), wiki %>
            </h4>
            <br/>
        <% end %>
    </div>
    <div class="col-md-4">
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
</div>

code/blocipedia/app/views/wikis/new.html.erb
<center><h1>New Wiki</h1></center>

<div class="row">
    <div class="col-md-8">
        <%= render partial: 'wikis/form' %>
    </div>
</div>

code/blocipedia/app/views/wikis/show.html.erb
<h1><%= markdown_to_html(@wiki.title) %>
    <p>
        <small>
            submitted <%= time_ago_in_words(@wiki.created_at) %> ago by <%= @wiki.user.name %>
        </small>
    </p>
</h1>

<br/>
 
<div class="row">
    <div class="col-md-8">
        <p><%= markdown_to_html(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
        <% if current_user == @wiki.user %>
            <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
        <% end %>
    </div>
</div>

<% if (@wiki.private && @wiki.user == current_user) || (@wiki.private && current_user.admin?) %>
    <%= render partial: 'collaborators/form' %>
<% end %>